"""use python uuid4 to generate uuid

Revision ID: 89886c359c34
Revises: d03f955f64d9
Create Date: 2025-04-24 01:33:09.668070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import sqlmodel package
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '89886c359c34'
down_revision: Union[str, None] = 'd03f955f64d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
