"""add created_at

Revision ID: 8b911dfbf612
Revises: 89886c359c34
Create Date: 2025-04-24 01:34:26.988181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import sqlmodel package
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8b911dfbf612'
down_revision: Union[str, None] = '89886c359c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
