"""initial revision

Revision ID: b32f9fbef9f8
Revises: 
Create Date: 2025-04-24 00:45:45.128367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import sqlmodel package
import sqlmodel

from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b32f9fbef9f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_provider', postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', name='accountprovider', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='accountprovider',
        new_values=['EMAIL', 'GOOGLE', 'GITHUB'],
        affected_columns=[TableReference(table_schema='public', table_name='accounts', column_name='account_provider')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='accountprovider',
        new_values=['GOOGLE', 'GITHUB'],
        affected_columns=[TableReference(table_schema='public', table_name='accounts', column_name='account_provider')],
        enum_values_to_rename=[],
    )
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
