"""add server default for uuid

Revision ID: d03f955f64d9
Revises: 0fb6a55d8a74
Create Date: 2025-04-24 01:30:17.931964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import sqlmodel package
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd03f955f64d9'
down_revision: Union[str, None] = '0fb6a55d8a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
