"""change to hashed_password

Revision ID: d5826ba28549
Revises: f74b18dba735
Create Date: 2025-04-09 18:20:41.194541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import sqlmodel package
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd5826ba28549'
down_revision: Union[str, None] = 'f74b18dba735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
